# SPDX-FileCopyrightText: Red Hat
# SPDX-License-Identifier: MIT

name: lint

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stylish:
    name: "black & flake8"
    runs-on: ubuntu-latest
    container:
      image: "registry.fedoraproject.org/fedora:43"

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install python3 and pip
        run: |
          dnf --setopt install_weak_deps=False install -y python3 python3-pip

      - name: Install test requirements
        run: pip install -r test-requirements.txt

      - uses: psf/black@87928e6d6761a4a6d22250e1fee5601b3998086e # 26.5.1
        with:
          version: "24.3.0"

      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@48819b39d57c621b5a64a1cdce40a5caa6a43b89 # v1

      - name: Run flake8
        run: |
          flake8
