name: lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  stylish:
    name: "black & flake8"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"
          cache-dependency-path: test-requirements.txt

      - name: Install test requirements
        run: pip install -r test-requirements.txt

      - uses: psf/black@stable
        with:
          version: "23.3.0"

      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1

      - name: Run flake8
        run: |
          flake8
