# SPDX-FileCopyrightText: Red Hat
# SPDX-License-Identifier: MIT

name: lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  stylish:
    name: "black & flake8"
    runs-on: ubuntu-latest
    container:
      image: "registry.fedoraproject.org/fedora:latest"

    steps:
      - uses: actions/checkout@v5

      - name: Install python3 and pip
        run: |
          dnf --setopt install_weak_deps=False install -y python3 python3-pip

      - name: Install test requirements
        run: pip install -r test-requirements.txt

      - uses: psf/black@stable
        with:
          version: "24.3.0"

      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1

      - name: Run flake8
        run: |
          flake8
