# SPDX-FileCopyrightText: Red Hat
# SPDX-License-Identifier: MIT

name: REUSE Compliance Check

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "registry.fedoraproject.org/fedora:43"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@772649cfa03a64a08c458c7cca9a6a473d74e7f9 # v6
